import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { CartProvider } from "@/context/CartContext";
import CartDrawer from "@/components/layout/CartDrawer";
import { WishlistProvider } from "@/context/WishlistContext";
import WishlistDrawer from "@/components/layout/WishlistDrawer";
import AccountDrawer from "@/components/layout/AccountDrawer";
import AuthInitializer from "@/components/AuthInitializer";
import { AccountProvider } from "@/context/AccountContext";

import { Toaster } from "react-hot-toast";
import SearchDrawer from "@/components/layout/SearchDrawer";
import { SearchProvider } from "@/context/SearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-full flex flex-col `}>
        <CartProvider>
          <WishlistProvider>
            <AccountProvider>
                <SearchProvider>
              <AuthInitializer />
              <Navbar />
              <CartDrawer />
              <WishlistDrawer />
              <AccountDrawer />
              <SearchDrawer />

              {children}
              <Toaster position="top-right" />
              </SearchProvider>
            </AccountProvider>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
